### ISSUE TITLE
Steam secondary path isn't loaded

### ISSUE THREAD

**Issue by xaberue** [ChustaSoft/GamerPlatformUtils#70]
Steam secondary path has wrong info and isn't loaded

**Comment by Arthus15** [comment]
Can you post your config and the path where you have the second folder so I can reproduce it?  @Xelit3

**Comment by xaberue** [comment]
> Can you post your config and the path where you have the second folder so I can reproduce it?  @Xelit3

Hi man!!

I already have assigned, it is fixed, it was a problem with a " in the path...

Pending to send PR

Thanks a lot bro!
